### ISSUE TITLE
Cannot drag root node into another root node when openIds is being used

### ISSUE THREAD

**Issue by phamquanganh31101998** [phphe/he-tree-react#2]
Hi, i'm using he-tree-react with datatype:'tree' and an array of openIds in useHeTree options. However I noticed the different between with and without openIds
- With openIds being used, it seems like I cannot drop a root level node into another root level node

https://github.com/phphe/he-tree-react/assets/43257497/52e1b629-7269-4eec-b4bf-50f76653d20a

- Without openIds, I can do that easily

https://github.com/phphe/he-tree-react/assets/43257497/f4330a89-4ed9-47ed-b28d-daa27817c014

My expectation is I can drag root level node into another root level node, with or without openIds.

**Comment by phphe** [comment]
check this: https://he-tree-react.phphe.com/v1/guide#open-when-dragging-over

**Comment by phamquanganh31101998** [comment]
Thank you! It worked for me.
